### ISSUE TITLE
Welcome to nginx!

### ISSUE THREAD

**Issue by juanitozambada** [PacktPublishing/Full-Stack-React-Projects-Third-Edition#87]
When i finished chapter 7 a test it, i made:
git push origin main

The Actions finished correctly, but when i open the blog-frontend in Google Cloud Service, the page open with the message:

Welcome to nginx!
If you see this page, the nginx web server is successfully installed and working. Further configuration is required.

For online documentation and support please refer to [nginx.org](http://nginx.org/).
Commercial support is available at [nginx.com](http://nginx.com/).

Thank you for using nginx.

I don't know the reason for that...

**Comment by omnidan** [comment]
@juanitozambada seems like something went wrong with the build. as specified in the Dockerfile, everything from the `dist` folder should be copied to the `/usr/share/nginx/html` directory, which then gets served by nginx. Can you please verify that everything worked well and provide logs of the actions?

additionally, please try to clone this project and deploy the `ch7` folder to see if that works for you. if it works fine, then compare the two projects and try to find a difference that might be causing this issue.

hope this helped you out! if you need further assistance, I need the logs and, ideally, access to your repository, so that I can check where things went wrong.

**Comment by bsingha27** [comment]
Hi @juanitozambada,
I hope Daniel's response has clarified your issue. 
We are closing this issue for now. If you encounter any further issues with the code, please feel free to open a new one.
Thanks.
