### ISSUE TITLE
ch9: build ci, run playwright fail

### ISSUE THREAD

**Issue by thanhtrungit25** [PacktPublishing/Full-Stack-React-Projects-Third-Edition#89]
Hi, 
When push to github action build, end to end show error when running playwright test.
But i run playwright at local is OK.
```
Run npx playwright test
  npx playwright test
  shell: /usr/bin/bash -e {0}

Error: Timed out waiting 1[2](https://github.com/thanhtrungit25/fullstack-node-react/actions/runs/12251667459/job/34176738627#step:7:2)0000ms from config.webServer.
```

Error: Process completed with exit code 1.

This is my playwright.config.js:

  webServer: {
    timeout: 120000,
    command: 'npm run e2e',
    url: 'http://localhost:5173',
    reuseExistingServer: !process.env.CI,
  },

Can anyone support me?
Thank you.

**Comment by omnidan** [comment]
Hi there @thanhtrungit25! I looked into the logs of your job and it seems like a timeout:

```
Error: Timed out waiting 120000ms from config.webServer.
```

This means that `npm run e2e` seems to have failed to start the app in GitHub Actions. Did you try locally running `npm run e2e` to see if there are any issues with your `e2e` setup?

To reproduce a GitHub Actions environment, try cloning the repo again and then execute the commands as specified in the YAML file.

**Comment by thanhtrungit25** [comment]
Hi @omnidan ,
Thank you for your response,
After traccing using config option:
  webServer: {
    command: 'npm run e2e',
    url: 'http://localhost:5173',
    port: port,
    reuseExistingServer: !process.env.CI,
    stdout: 'pipe',
    stderr: 'pipe',
  },
I think i miss port variable using process.env.PORT
Because i did not upload this .env file to my github sourcecode

Can you explain me why you push this .env to github?

Thank you

**Comment by omnidan** [comment]
@thanhtrungit25 you do not need to push `.env` to GitHub, but it would also be fine to do so. I have seen both practices in use:

- Push `.env` with some default env vars (do not put secrets in there!) and then override others in the CI config
- Do not push any env vars by default and set all of them in the CI config

So, you need to decide to either push the `.env` file (easiest solution) or set the environment variables in GitHub Actions, see: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables#defining-environment-variables-for-a-single-workflow

Please let me know if it works with the `PORT` env var set so that I can close the issue ☺️

**Comment by thanhtrungit25** [comment]
@omnidan 
Yeah it's work. ☺️
Thank you so much. 
Have a nice day.

**Comment by omnidan** [comment]
Glad you were able to solve it, have a nice day too!
